heat_template_version: 2014-10-16

description: >
  This is a nested stack that defines a single Mesos node. This stack is
  included by a ResourceGroup resource in the parent template
  (mesoscluster.yaml).

parameters:

  server_image:
    type: string
    description: glance image used to boot the server

  server_flavor:
    type: string
    description: flavor to use when booting the server

  ssh_key_name:
    type: string
    description: name of ssh key to be provisioned on our server

  availability_zone:
    type: string
    description: availability zone in which to spawn the cluster

  network:
   type: string
   description: Network id/nane

  server_name:
   type: string
  
  security_groups:
    type: comma_delimited_list

resources:
  
  #########
  # Float IP
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: ext-net

  mesos_server_eth0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      security_groups: {get_param: security_groups}
      replacement_policy: AUTO

  mesos_server:
    type: OS::Nova::Server
    properties:
      name: {get_param: server_name}
      image: {get_param: server_image}
      flavor: {get_param: server_flavor}
      availability_zone: {get_param: availability_zone}
      key_name: {get_param: ssh_key_name}
      networks:
        - port: {get_resource: mesos_server_eth0}
      user_data_format: SOFTWARE_CONFIG
  
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: mesos_server }

outputs:

  mesos_server_ip:
    value: {get_attr: [mesos_server_eth0, fixed_ips, 0, ip_address]}

  mesos_server_id:
    value: {get_resource: mesos_server}
